### PR TITLE
Review `index.md` arabic translation

### PR DESCRIPTION
**Pull request by atefBB**

### CODE REVIEW

**Comment by atefBB** [comment]
<div dir="rtl">إصلاح أخطاء إملائية.</div>

**Comment by OmarioHasan** [comment]
@atefBB  thank you Atef, can you please accept CALassistant to merge this changes safely

**Comment by atefBB** [comment]
@OmarioHasan DONE!

**Comment by OmarioHasan** [comment]
@atefBB thank you again and waiting for your big topics 🔥🔥🔥

**Pull request merged**
