### PR TITLE
styles and classes

### PR DESCRIPTION
**Pull request by abdelrhmanali29**

### CODE REVIEW

**Comment by atefBB** [comment]
@abdelrhmanali29 The translation has conflicts with the `master` branch, plz fix it and send a `proper` PR.
Thank you.

**Comment by abdelrhmanali29** [comment]
@atefBB  How I can solve this conflict ?

**Review by OmarioHasan — COMMENTED** [review]
@atefBB I can't see any conflicts, where it, please

**Comment by OmarioHasan** [comment]
@abdelrhmanali29 thanks for your contribution, you can do more 🚀

**Pull request merged**
